---
- name: Install and configure prerequisites for freeIPA
  hosts: file-server
  become: true

- ansible.builtin.import_playbook: update_configure_system.yml
- ansible.builtin.import_playbook: config_ipa_nfs.yml
- ansible.builtin.import_playbook: config_nfs.yml
- ansible.builtin.import_playbook: config_ipa_automount.yml
