---
- name: Install and configure prerequisites for freeIPA
  hosts: ipa-server
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: Update packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Add self to /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "192.168.60.4 ipa-server.ipa.test ipa-server"
        state: present

- name: Configure firewalld
  hosts: ipa-server
  become: true
  vars_files:
    - vars.yml

  tasks:
    - name: Start Firewalld service
      ansible.builtin.systemd:
        name: firewalld
        state: started

    - name: Allow freeIPA services
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
      loop: "{{ freeipa_services }}"

    - name: Allow specific TCP ports
      ansible.posix.firewalld:
        port: "{{ item }}/tcp"
        permanent: true
        state: enabled
      loop: "{{ tcp_ports }}"

    - name: Allow specific UDP ports
      ansible.posix.firewalld:
        port: "{{ item }}/udp"
        permanent: true
        state: enabled
      loop: "{{ udp_ports }}"

    - name: enable firewalld
      ansible.posix.firewalld:
        state: enabled


- name: Playbook to configure IPA server
  hosts: ipa-server
  become: true
  vars_files:
    - vars.yml

  roles:
    - role: freeipa.ansible_freeipa.ipaserver
      state: present
