---
- name: Install and initialize PostgreSQL
  hosts: db-server
  become: true

  tasks:
    - name: Install PostgreSQL packages
      ansible.builtin.dnf:
        name: "{{ item }}"
      loop:
        - postgresql
        - postgresql-server

    - name: See if PostgreSQL is initialized
      ansible.builtin.stat:
        path: "/var/lib/pgsql/data/pg_hba.conf"
      register: postgres_data

    - name: Initialize PostgreSQL
      shell: "postgresql-setup initdb"
      when: not postgres_data.stat.exists

    - name: Start PostgreSQL service
      ansible.builtin.service:
        name: postgresql
        state: started
        enabled: true
