---
- name: Download and install ipa-client
  hosts: db-server
  become: true
  roles:
    - role: freeipa_client

- name: Add db-server as an IPA service postgres/db-server.ipa.test
  hosts: db-server
  tasks:
    - name: Make sure service is present
      freeipa.ansible_freeipa.ipaservice:
        ipaadmin_password: adminpass
        name: postgres/db-server.ipa.test
        state: present

# Use shell rather than command in order to keep our kerberos ticket
- name: Obtain Kerberos ticket and retrieve keytab
  hosts: db-server
  become: true
  tasks:
    - name: Run kinit command to obtain Kerberos ticket
      ansible.builtin.shell: echo 'adminpass' | kinit admin
      register: kinit_result

    - name: Check if kinit command succeeded
      ansible.builtin.debug:
        msg: "Kinit failed!"
      when: kinit_result.rc != 0

    - name: Retrieve Kerberos keytab using ipa-getkeytab
      ansible.builtin.shell: ipa-getkeytab -s ipa-server.ipa.test -p postgres/db-server.ipa.test -k /var/lib/pgsql/data/pg.keytab
      when: kinit_result.rc == 0 

    - name: Change ownership of pg.keytab file
      ansible.builtin.file:
        path: /var/lib/pgsql/data/pg.keytab
        owner: postgres
        group: postgres
