---
- name: Install and configure PSQL and GSS configuration
  hosts: db-server
  become: true
  vars_files:
    - vars.yml

  roles:
    - role: geerlingguy.postgresql

  tasks:
    - name: Configure keytab and listen adresses for PSQL
      ansible.builtin.blockinfile:
        path: /var/lib/pgsql/data/postgresql.conf
        block: |
          listen_addresses = '*'
          krb_server_keyfile = '/var/lib/pgsql/data/pg.keytab'
