---
#PSQL variables
postgresql_user: postgres
postgresql_group: postgres
postgresql_restarted_state: "restarted"
postgresql_service_state: started
postgresql_service_enabled: true
postgresql_hba_entries:
  - { type: local, database: all, user: postgres, auth_method: peer }
  - { type: local, database: all, user: all, auth_method: peer }
  - { type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: gss, auth_options: 'include_realm=0'}
  - { type: host, database: all, user: all, address: '192.168.60.0/24', auth_method: gss, auth_options: 'include_realm=0'}